### ISSUE TITLE
[UI] Text Not Visible

### ISSUE THREAD

**Issue by d2Dreamer** [TowneSquare/RENA#36]
Title text overlays with background of same colour - thus not visible.

https://github.com/TowneSquare/RENA/assets/41088824/2e3b3509-9ee5-4df4-b0b9-10d10ecb220b

**Comment by codewizard870** [comment]
@markots  
we are using static background and need to use it.

**Comment by codewizard870** [comment]
Can you please make me bg for over 2k screen?

**Comment by markots** [comment]
done
