### ISSUE TITLE
If the users checks "Don't show this dialog again" and proceeds, he shouldn't see this popup the next time he Liquifies an NFT. This can be stored locally in cookies

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/RENA#37]
<img width="669" alt="Screenshot 2024-03-27 at 11 22 06" src="https://github.com/TowneSquare/RENA/assets/139227890/734f6573-f274-421b-a140-dc4aaa420385">

**Comment by ddamazz** [comment]
https://github.com/TowneSquare/RENA/assets/139227890/5148e8ec-ba7c-4efb-8d02-2f4f905a151c

I still see the popup even tho I've chekd "Don't show" and have proceeded

**Comment by codewizard870** [comment]
Can you refresh and retry again?
