### ISSUE TITLE
If the presale has started, it should be displayed that the presale is LIVE and bellow should be the counter that shows when the presale ends

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/RENA#52]
<img width="499" alt="Screenshot 2024-04-02 at 22 13 29" src="https://github.com/TowneSquare/RENA/assets/139227890/ce8b8e41-c102-4689-982e-33149b85e81a">
<img width="297" alt="Screenshot 2024-04-02 at 22 14 04" src="https://github.com/TowneSquare/RENA/assets/139227890/3750f78d-0bbe-4257-a807-bba4a8c0c85b">

**Comment by Aladeenb** [comment]
Issue fixed and will be pushed in the next Vercel build.
