### ISSUE TITLE
By default "Total raised" should be "0" (not 00000000)

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/RENA#53]
<img width="381" alt="Screenshot 2024-04-02 at 22 19 04" src="https://github.com/TowneSquare/RENA/assets/139227890/2aea6d32-71b1-4fb7-a96a-d7f9605ce0b1">

**Comment by Aladeenb** [comment]
Hey @ddamazz , this was indeed different from the what's set on Figma, but I think showing decimals is important to keep things accurate and transparent. 

There surely will be cases where contributions amounts are not a rounded number. 

This is ofc is up for discussion.

**Comment by Aladeenb** [comment]
Issue fixed and will be pushed in the next verse
