### ISSUE TITLE
It's not possible to insert "." in the input field making it impossible to insert 1.0001 APT for example

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/RENA#54]
<img width="484" alt="Screenshot 2024-04-03 at 12 23 02" src="https://github.com/TowneSquare/RENA/assets/139227890/7cd7698d-6af7-4609-b2ce-dac125a26fa2">

**Comment by codewizard870** [comment]
@ddamazz   so we should make it to allow to input 0.002 for example?

**Comment by ddamazz** [comment]
@codewizard870 yes exactly, tnx

**Comment by ddamazz** [comment]
@codewizard870 it should only be possible to insert numbers "1 2 3 4 5 6 7 8 9 0" and dot "."
Bo other characters should be allowed (letters and other symbols)

**Comment by codewizard870** [comment]
@Aladeenb  
Can you check the last commit please?
About : "Currently you can only send 1.24 APT. If you insert 1.245 it gives you an error"

**Comment by codewizard870** [comment]
It's fixed all on my side.
rest of thing is not sure as it's about @Aladeenb

About : "Currently you can only send 1.24 APT. If you insert 1.245 it gives you an error"

**Comment by Aladeenb** [comment]
That issue was related to how "count"  from `contribute` is passed - It won't allow for float numbers with 2 decimals as input: `await contribute(account.address, count);`

Passing it as float fixed the issue:
`await contribute(account.address, parseFloat(count));`
