### ISSUE TITLE
If the Presale is LIVE, and the wallet has been connected, the button should say SEND APT

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/RENA#57]
<img width="503" alt="Screenshot 2024-04-03 at 12 28 38" src="https://github.com/TowneSquare/RENA/assets/139227890/1e1d2a61-3909-4b75-a0ae-7f7207b1a3b5">

**Comment by ddamazz** [comment]
@codewizard870 pls update to "Send APT" not Aptos, thanks

**Comment by codewizard870** [comment]
@markots
