### ISSUE TITLE
Trait name should fit the box

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/RENA#60]
<img width="342" alt="Screenshot 2024-04-03 at 18 37 52" src="https://github.com/TowneSquare/RENA/assets/139227890/3348292e-01e7-4bfa-8e06-1ee9201042df">

**Comment by ddamazz** [comment]
<img width="501" alt="Screenshot 2024-04-04 at 10 36 39" src="https://github.com/TowneSquare/RENA/assets/139227890/0ba678cb-f4dc-4007-88a3-13e960563660">
please don't make the height fixed. Make the box height fit the content, i.e. it should have less height if the Trait name is in just 1 line, and it should be higher if the Trait name goes in 2 lines @codewizard870

**Comment by markots** [comment]
done
