### ISSUE TITLE
[MOBILE] Fix the overlay bug when inserting the amount

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/RENA#61]
https://github.com/TowneSquare/RENA/assets/139227890/6ed568ca-dc17-4a94-b407-c73677a71d99

**Comment by codewizard870** [comment]
@ddamazz  I can't see such issues.

**Comment by markots** [comment]
@Aladeenb can you make presale live please so we can test this issue? Thanks

**Comment by markots** [comment]
done
