### ISSUE TITLE
Display available NFT claim amount without decimals

### ISSUE THREAD

**Issue by markots** [TowneSquare/RENA#63]
Please take out the decimals from the available amount to claim an NFT. 

Current state
<img width="1263" alt="Screenshot 2024-04-08 alle 16 38 20" src="https://github.com/TowneSquare/RENA/assets/112094900/9d21ce43-8378-4142-a129-326d8559630b">

**Comment by Aladeenb** [comment]
Done. The next Vercel will include the fix.

**Comment by markots** [comment]
@codewizard870 when user click on available NFTs to claim, the input field is showing the number with decimal. please take out the decimals.
<img width="733" alt="Screenshot 2024-04-10 alle 09 01 55" src="https://github.com/TowneSquare/RENA/assets/112094900/5c654724-83e5-47aa-9d34-a88c5b8ae0a5">

**Comment by codewizard870** [comment]
@markots 
It's pushed just now.

**Comment by markots** [comment]
@codewizard870 now, when I click on "8 renegades" it's showing me 9 in the input field. 
<img width="682" alt="Screenshot 2024-04-10 alle 10 17 08" src="https://github.com/TowneSquare/RENA/assets/112094900/6865f1d5-a4b3-48ea-960b-5c3e7701efcf">

**Comment by markots** [comment]
done
