### ISSUE TITLE
Show only 4 decimals of the RENA balance

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/RENA#64]
<img width="900" alt="Screenshot 2024-04-08 at 23 13 45" src="https://github.com/TowneSquare/RENA/assets/139227890/b0ca3b43-b977-4945-aa18-73a1b9672a87">

it should be just "18.5269", so 4 decimals, the rest is hidden

**Comment by Aladeenb** [comment]
Done. The next Vercel build will include the fix.
