### ISSUE TITLE
Please update the Presale page when the Presale has ended

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/RENA#65]
1. Update the title to "$RENA Presale"
2. Add "My $RENA" (balance with 4 decimals)
3. Thank you for participating instead of the counter

https://www.figma.com/file/HCcZsSh4PPIBtAWej4WYnR/RENEGADES---Liquid-NFT?type=design&node-id=834%3A9790&mode=design&t=fEcEtP0b0shtaX2g-1

<img width="444" alt="Screenshot 2024-04-09 at 11 47 22" src="https://github.com/TowneSquare/RENA/assets/139227890/b2f7700b-d0ca-4288-aae5-a444babf1c08">

**Comment by ddamazz** [comment]
@Aladeenb do you need to provide something for the "My $RENA" part or is this just FE?

**Comment by Aladeenb** [comment]
Fixed. @codewizard870 will probably need to fix the padding/margin so it aligns with the Figma.

**Comment by ddamazz** [comment]
@Aladeenb @codewizard870  can you also please change the button to "Send APT", currently it says Get RENA coming soon. The button should be disabled as is
<img width="480" alt="Screenshot 2024-04-10 at 11 58 42" src="https://github.com/TowneSquare/RENA/assets/139227890/6c7989a5-a16b-4f35-b0bf-743722b81c99">

**Comment by markots** [comment]
> @Aladeenb @codewizard870 can you also please change the button to "Send APT", currently it says Get RENA coming soon. The button should be disabled as is <img alt="Screenshot 2024-04-10 at 11 58 42" width="480" src="https://private-user-images.githubusercontent.com/139227890/321189437-6c7989a5-a16b-4f35-b0bf-743722b81c99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjAxOTcsIm5iZiI6MTcxMjgxOTg5NywicGF0aCI6Ii8xMzkyMjc4OTAvMzIxMTg5NDM3LTZjNzk4OWE1LWExNmItNGYzNS1iMGJmLTc0MzcyMmI4MWM5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQwNzE4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmQxNzI2ZWFmNWNiN2NlMDMyMzJhOWM2YzQwOGFmOTRhN2VmYmEyMDY1OWUwYjU2ZjBmYmFhZTdjNDlkMDhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G1_VjCPROHQkXfaDIHSlW7rnCTgtWilzklj8EF4QqxE">

@codewizard870 this is still missing on FE

**Comment by markots** [comment]
done
