### ISSUE TITLE
Implement Batch liquify

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/RENA#66]
https://github.com/TowneSquare/RENA/assets/139227890/87358f1c-f900-4142-92ba-3a96140e6ecd

Design https://www.figma.com/file/HCcZsSh4PPIBtAWej4WYnR/RENEGADES---Liquid-NFT?type=design&node-id=1105%3A6833&mode=design&t=fEcEtP0b0shtaX2g-1

NOTE:
1. [Check assets ](https://www.figma.com/file/HCcZsSh4PPIBtAWej4WYnR/RENEGADES---Liquid-NFT?type=design&node-id=1105%3A6825&mode=design&t=fEcEtP0b0shtaX2g-1) The checkmark has a transparent layer underneath 
2. The user can Liquify 1 or more NFTs using Batch liquify. Note that the button label changes if the user has selected 1 NFT or multiple NFTs
3. Deselect all link deselects all checkmarks
4. The Liquify button and the gray div have a slide in animation as in the video
5. This div is positioned above other elements on the page and is ancored to the bottom of the screen
6. 
<img width="300" alt="Screenshot 2024-04-09 at 12 24 26" src="https://github.com/TowneSquare/RENA/assets/139227890/83b6a33f-bafe-4009-8138-f5c60c88fe5f"> Liquify pop up has different text if the user has selected more than 1 NFT to liquify. Changes: Title, Body text, Button label, text under RENA icon, Orange tag "+X more"
7. Deselect link Hover -> Orange color

**Comment by ddamazz** [comment]
@codewizard870 pls go through all the NOTES and double check them before marking the issue as Done :) thanks

**Comment by markots** [comment]
Fix the popup height. It should be visible entirely
![image](https://github.com/TowneSquare/RENA/assets/112094900/0c4b3343-8649-4991-ac26-d60f1e362939)

**Comment by markots** [comment]
done
