### ISSUE TITLE
Fix the claim popup

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/RENA#67]
Currently it's like this
<img width="699" alt="Screenshot 2024-04-10 at 11 06 59" src="https://github.com/TowneSquare/RENA/assets/139227890/8fc988d2-7056-4004-9b63-11b3a5b5f104">

it should be like this
<img width="693" alt="Screenshot 2024-04-10 at 11 05 09" src="https://github.com/TowneSquare/RENA/assets/139227890/8a8880c2-2cb5-4e62-8035-79a9faaeca60">

Also update the Title of the popup as in design

**Comment by markots** [comment]
done
