### ISSUE TITLE
Fix the No Claim banner 

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/RENA#8]
design https://www.figma.com/file/HCcZsSh4PPIBtAWej4WYnR/RENEGADES---Liquid-NFT?type=design&node-id=270%3A35839&mode=design&t=txKjpbtEsAcvKTYE-1

<img width="900" alt="Screenshot 2024-03-11 at 13 31 04" src="https://github.com/TowneSquare/RENA/assets/139227890/75910f4a-74b1-42bf-80c2-28a77b2d0634">
->

<img width="730" alt="Screenshot 2024-03-11 at 13 31 21" src="https://github.com/TowneSquare/RENA/assets/139227890/cd6beab1-9972-4dd2-9ec8-59b4f1f3dd62">

**Comment by codewizard870** [comment]
It would be done with API integration as it need state for it.
