### ISSUE TITLE
Updated grid tiles on the Homepage

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/RENA#9]
<img width="900" alt="Screenshot 2024-03-11 at 13 49 08" src="https://github.com/TowneSquare/RENA/assets/139227890/ad61e9c7-3851-4025-ba6e-3135ae39635f">

Please change the tiles behind the **Menu links** and **Connect wallet** button from R to empty ones to increase legibility

**Comment by codewizard870** [comment]
useEffect(() => {
    const length = windowWidth < 760 ? 80 : 300;
    setItems(Array.from({ length }, () => Math.random() < 0.7));
  }, [windowWidth]);

  return (
    <div className="w-[150vw] -ml-14 -mt-20">
      <div className="bg-[#121212] flex min-w-[150vw] flex-wrap">
        {items.map((isActive, index) =>
          isActive ? <ActivedItem key={index} /> : <InactivedItem key={index} />
        )}
      </div>
    </div>
  );
};

**Comment by codewizard870** [comment]
![image](https://github.com/TowneSquare/RENA/assets/91666375/7b5b094d-f360-46df-afaa-4af69db0ca2f)

**Comment by codewizard870** [comment]
Currently It simply creating randomly every time it's rendering.
But in that case, I need to make it manually.

This one is okay like you said about header side.
Let me add it manually for this one.
But there shouldn't be more. let me know so.
@ddamazz

**Comment by ddamazz** [comment]
<img width="854" alt="Screenshot 2024-03-12 at 20 29 47" src="https://github.com/TowneSquare/RENA/assets/139227890/5be6ea62-a9dc-4916-9ee7-7efc981b8a33">

@codewizard870 great, can you pls also add empty circles under My Renegades and the Connect/Wallet button pls? the rest of the random generating grid is great tnx

**Comment by ddamazz** [comment]
<img width="900" alt="Screenshot 2024-03-13 at 17 04 12" src="https://github.com/TowneSquare/RENA/assets/139227890/aa440c87-3006-4902-87bc-b58f44f8ba41">
@codewizard870 it's still the same

**Comment by codewizard870** [comment]
It's done.
